### ISSUE TITLE
Docker organizations

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/crowbar-openstack#10]
Use different settings for docker hub and custom registry.

**Comment by shimizuf** [comment]
Different settings now work. The default is our standard Dockerhub organization. If the Operator sets a custom registry, they must enter their own organization. This organization is then set - along with the other custom registry settings - in the Compose files.

**Comment by GoebelL** [comment]
This issue was moved to servicecatalog/crowbar-escm#10
