### ISSUE TITLE
Updating the ESCM

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/crowbar-openstack#13]
With the current implementation, Chef run will always trigger the deployment script even without changes.
The effect is that the ESCM services are restarted periodically.

Inject a configuration files which contains the current configuration and the version of deployment script.

**Comment by StavrevaS** [comment]
The script copies the applied configuration before exit. At the next start the new configuration is compared to the current one. The ESCM is updated only if difference is found.

**Comment by GoebelL** [comment]
This issue was moved to servicecatalog/crowbar-escm#13
