### ISSUE TITLE
ESCM setup log file

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/crowbar-openstack#17]
The log of the ESCM setup (VM configuration, docker pull, docker start...) is kept in the VM and with each run of the deployment script, it is overwritten. This should be improved in order to have the history of changes for troubleshooting purposes.

The log file should be opened in append mode for logging and maybe kept with other log files in the logs cinder volume.

**Comment by shimizuf** [comment]
Setup log moved to cinder volume in cfee582c919df89caa18b96b19ab18e4bf768c5a

**Comment by shimizuf** [comment]
Done.

**Comment by GoebelL** [comment]
This issue was moved to servicecatalog/crowbar-escm#17
