### ISSUE TITLE
Docker registry settings

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/crowbar-openstack#2]
The docker registry settings:
- use_registry - boolean flag if other registry than docker hub should be used
- host
- port
- auth
- user
- password

The following issues still exist:
- Remove use_registry, registry must always be specified, default is docker hub if the host and port are empty.
- Not all registry settings are forwarded to the Heat template and cloud init scripts
- Check how empty values are handled (if docker hub used)

Still not clear if certificates need to be installed (if custom solution for docker registry will be used).

**Comment by StavrevaS** [comment]
The following solution is implemented:

the oscm barclamp gives a possibility to choose between docker hub or other docker host (host, port)
Authentication (user, pwd) is offered for both cases. In case of custom docker registry, insecure connection is implemented for the first release.

**Comment by GoebelL** [comment]
This issue was moved to servicecatalog/crowbar-escm#2
