### ISSUE TITLE
Disable container logging to messages

### ISSUE THREAD

**Issue by shimizuf** [servicecatalog/crowbar-openstack#24]
On the Docker instance we configure rsyslog to write container logs to dedicated log files on the Cinder logs volume. But currently the container logs are also written to /var/log/messages which is redundant and fills the instance's file system. We must disable container logging to the messages file.

**Comment by shimizuf** [comment]
Done.

**Comment by GoebelL** [comment]
This issue was moved to servicecatalog/crowbar-escm#24
