### ISSUE TITLE
Display EULA in UI

### ISSUE THREAD

**Issue by shimizuf** [servicecatalog/crowbar-openstack#31]
We must display the EULA in the Barclamp UI.

**Comment by shimizuf** [comment]
Did some tests and the best place to put the EULA and/or link to the EULA is in the Haml template crowbar_framework/app/views/barclamp/escm/_edit_attributes.html.haml. It's possible to use the existing style info as well as use hyperlinks or Javascript.

**Comment by GoebelL** [comment]
This issue was moved to servicecatalog/crowbar-escm#31
