### ISSUE TITLE
Proxy settings - no_proxy

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/crowbar-openstack#9]
The no_proxy setting should have static part set by barclamp (localhost, floating_ip, docker hosts for internal communication) and public part set by operator on UI.

**Comment by shimizuf** [comment]
This concerns the no_proxy setting for Tomcat, not Docker.

**Comment by shimizuf** [comment]
- This functionality works for Docker settings
- For the application (TomEE) this depends on servicecatalog/oscm-dockerbuild/issues/37 and additionally the oscm-deployer and var.env must be extended to contain the necessary proxy variables

**Comment by GoebelL** [comment]
This issue was moved to servicecatalog/crowbar-escm#9
